### PR TITLE
Adding Newsletter form.

### LINKED ISSUE #1: Missing Newsletter Form
This coming soon website is missing a newsletter form.

### PR DESCRIPTION
**Pull request by Abhishek07-0302**

### CODE REVIEW

**Comment by sumeetweb** [comment]
Good job @Abhishek07-0302. 👍

**Comment by Abhishek07-0302** [comment]
> Good job @Abhishek07-0302. 👍

Thank you.

**Comment by Abhishek07-0302** [comment]
image

**Comment by Abhishek07-0302** [comment]
Is this repo not participating in the hacktoberfest?

**Comment by sumeetweb** [comment]
> Is this repo not participating in the hacktoberfest?

It's participating.

**Comment by sumeetweb** [comment]
image

Newsletter form is added in html but not visible. I think it needs some work with CSS. Can you please check?

**Pull request merged**
